
default_platform(:android)

# To run the lane, execute the following command:
# bundle exec fastlane firebase_distribution

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor prod --target lib/main_prod.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:804034502617:android:da5303cbcc6c24d2cd83c8",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-prod-release.apk",
        testers: "Bekkaysouhaib1996@gmail.com",
        release_notes: "This is a test release note for the fastlane",
  )
  end
end
